services:
  - type: web
    name: raxmonov-save-bot
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    healthCheckPath: /
    
